### ISSUE TITLE
F2: Agregar el sistema de puntuación de la colección y libros

### ISSUE THREAD

**Issue by KennethUlloa** [GR1SW-VyV/online-library#54]
Redefinir la especificación de los steps para que concuerde con el sistema de puntos. @Sebascerboni 
Implementar el manejo de puntos en la colección. @FrankzAlarcon

**Comment by FrankzAlarcon** [comment]
Primera versión de los métodos ya están creados y subidos al repositorio.
Quedo a la espera de si se necesitan modificaciones en los mismos

**Comment by FrankzAlarcon** [comment]
Le hice refactor a los métodos creados, con las recomendaciones recibidas:
3071694df27eb7b87349e86e6b7235b5cfbaea5b

**Comment by Sebascerboni** [comment]
Implementación del sistema de puntos de la colección incorporadas exitosamente. También se creo un escenario especifico para probar este nueva funcionalidad. No hay novedades
